version: '3.8'

services:
  db:
    container_name: db
    image: postgres:14.5-alpine
    privileged: true
    restart: always
    ports:
      - 1405:5432
    environment:
      - POSTGRES_PASSWORD=1405
      - POSTGRES_USER=postgres
      - POSTGRES_DB=innopolis
  backend:
    container_name: backend
    build: .
    ports:
      - 8000:8000
    command:
      bash -c "python manage.py migrate &&
      gunicorn core.wsgi -b 0.0.0.0:8000"
    depends_on:
      - db