version: '3.8'

services:
  backend:
    container_name: backend
    build: .
    ports:
      - 8000:8000
    command:
      bash -c "python manage.py migrate &&
      gunicorn core.wsgi -b 0.0.0.0:8000"