# Generated by Django 3.2.15 on 2022-09-10 08:18

from django.db import migrations
from mixer.backend.django import mixer


def fill_table_item(*args, **kwargs):
    mixer.cycle(12).blend('stripeapp.itemmodel',
                          name=mixer.sequence('product_{0}'),
                          description=mixer.sequence('description_{0}'),
                          price=mixer.sequence('10{0}'))


class Migration(migrations.Migration):
    dependencies = [
        ('stripeapp', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(fill_table_item),
    ]
